name: Merrill Photography
favicon: null
layout_spectrum: 0.5016910105478019
typography_spectrum: 0.44236902496777475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.025009542237967253
  lightness: 0.03678271803073585
  saturation: 0.03636754956096411
  rhythmicContrast: 0.6114711838308722
purpose: []
