name: Merrill Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34218
title: Merrill Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7c7c7'
    - '#a2a2a2'
    - '#787878'
    - '#5c5c5c'
    - '#131313'
  brandStrength: 0.375
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
